### ISSUE TITLE
LLVM 9.0.0 support.

### ISSUE THREAD

**Issue by qis** [CraneStation/wasi-sdk#41]
It is not possible to build `wasi-sdk` with LLVM 9.0.0.

```
In file included from /home/qis/wasi/src/wasi-libc/libc-bottom-half/crt/crt1.c:1:
In file included from /LLVM/share/wasi-sysroot/include/stdlib.h:6:
In file included from /LLVM/share/wasi-sysroot/include/__functions_malloc.h:7:
/LLVM/share/wasi-sysroot/include/stddef.h:30:15: fatal error: 'stddef.h' file not found
#include_next <stddef.h>
              ^~~~~~~~~~
1 error generated.
Makefile:416: recipe for target 'startup_files' failed
```

It may be a good idea to start a `trunk` branch that targets the latest LLVM as both, a preparation for the next release and for making it easier for users to experiment with new compiler features in the browser.

**Comment by sunfishcode** [comment]
So far we have been attempting to support both LLVM 8.0 and 9.0 in the same branch; see the `CLANG_VERSION` variable and its uses for some examples. If possible, it'd be nice to keep doing that, so that we don't have to maintain two branches, however it'll depend on what kinds of changes we end up needing for LLVM 9.0.

I'm not able to reproduce the specific error you reported here, but I am able to reproduce a bunch of diffs reported in predefined-macros.txt when compiling with clang 9.0.0. The suggestion [here](https://github.com/CraneStation/wasi-libc/pull/75#issuecomment-505134740) might be a way forward for that.

**Comment by sbc100** [comment]
We build and test wasi-libc constantly with LLVM tip of tree here: https://wasm-stat.us/console

I've not seen this issue.  

Can you post your full command line and full output (with '-v' added if possible).

**Comment by qis** [comment]
Oh, so I shouldn't have replaced `8` with `9` in the `Makefile`? Sorry. Will try again later.

**Comment by qis** [comment]
@sbc100 Wow. I was particularly interested in a minimal C++20 toolchain for a windows host that targets wasm.

Looks like the builder you linked supports that. Is there some documentation on how to reproduce it or do I have to try to guess how to use `wasm_llvm.py`?

I have experience in building chromium, so that wouldn't be too bad, but proper instructions are always preferred.

**Comment by sbc100** [comment]
We currently have two waterfalls building upstream llvm:
https://ci.chromium.org/p/wasm/g/toolchain/console
https://ci.chromium.org/p/emscripten-releases

Sadly only the former includes wasi (the later is basically for emscripten) but only the later published its output binaries.   Also it looks like the former doesn't build wasi on windows.

So your best bet is to continue to try to make this repo (wasi-sdk) build with windows and llvm-9.0.   I don't have any experience building wask-sdk.. only wasi-libc.

**Comment by sunfishcode** [comment]
Our goal is to support Windows and LLVM 9.0 with wasi-sdk, and in theory it should be pretty close; it's just a matter of us finding time and/or people to help us debug the issues and fix them.

**Comment by qis** [comment]
Still can't build it on Linux. This is how I tried it:

```sh
git clone --depth 1 https://github.com/CraneStation/wasi-sdk
git clone --depth 1 https://github.com/llvm/llvm-project wasi-sdk/src/llvm-project
git clone --depth 1 https://github.com/CraneStation/wasi-libc wasi-sdk/src/wasi-libc
sed -i 's/share\/wasi-sysroot/sysroot/g' wasi-sdk/Makefile
cd wasi-sdk
make PREFIX=/opt/wasi -j4
make PREFIX=/opt/wasi
# Will error out because of the `check` target.
touch build/wasi-libc.BUILT
make PREFIX=/opt/wasi
# Will error out because `stdlib.h` cannot be found for `include_next`.
```

Last error message:
```
/opt/wasi/bin/clang --target=wasm32-wasi --sysroot=/opt/wasi/share/wasi-sysroot -DVISIBILITY_HIDDEN  -O1 -fdebug-prefix-map=/home/xnet/wasi-sdk=wasisdk://v -O2 -g -DNDEBUG    -std=c11 -fno-builtin -fvisibility=hidden -fomit-frame-pointer -o CMakeFiles/clang_rt.builtins-wasm32.dir/int_util.c.obj   -c /home/xnet/wasi-sdk/src/llvm-project/compiler-rt/lib/builtins/int_util.c
/home/xnet/wasi-sdk/src/llvm-project/compiler-rt/lib/builtins/int_util.c:57:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^~~~~~~~~~
```

**Comment by sunfishcode** [comment]
This line:

> sed -i 's/share\/wasi-sysroot/sysroot/g' wasi-sdk/Makefile

is unusual. Can you comment on why you need this?

**Comment by sunfishcode** [comment]
FYI, https://github.com/CraneStation/wasi-libc/pull/84 just landed, which should fix the main "make check" failure with LLVM 9.0.

**Comment by sbc100** [comment]
BTW, wasi-sdk uses git submodules so it better to use `git submodule` to clone the dependencies.  I believe you can still do a shallow clone if you prefer that using `git clone --recurse-submodules --shallow-submodules`

**Comment by qis** [comment]
@sunfishcode I do that (you forgot the backspace) to have a specific toolchain directory layout. The `share` directory and `wasi` prefix are kind of pointless in a single-cross-compilation-target toolchain installation.

CraneStation/wasi-libc#84 is good, but I don't see how it can fix the other errors since I simulated a success with `touch(1)`.

I'll go ahead and try it again without modifying the `Makefile`.

@sbc100 I can't do that if I want llvm from trunk. Even worse, `src/llvm-project` points to 8.0.1 (from 2 months ago).

**Comment by sbc100** [comment]
I just did a sync to head of wasi-libc and llvm-project and run `make PREFIX=$HOME/install` and it worked just fine.

I think your problem is that you didn't actually install wasi-libc because you did `touch build/wasi-libc.BUILT`.  The check that was failing in wasi-libc happens before it installs anything.

**Comment by sbc100** [comment]
wasi-libc roll is https://github.com/CraneStation/wasi-sdk/pull/43

**Comment by qis** [comment]
I could build a toolchain for Windows.

1. WSL

```sh
git clone --depth 1 https://github.com/CraneStation/wasi-sdk
git clone --depth 1 https://github.com/llvm/llvm-project wasi-sdk/src/llvm-project
git clone --depth 1 https://github.com/CraneStation/wasi-libc wasi-sdk/src/wasi-libc
git clone --depth 1 https://git.savannah.gnu.org/git/config wasi-sdk/src/config
sed -i 's/share\/wasi-sysroot/sysroot/g' wasi-sdk/wasi-sdk.cmake
sed -i 's/share\/wasi-sysroot/sysroot/g' wasi-sdk/Makefile
make -C wasi-sdk PREFIX=/opt/wasi -j4
git clone wasi-sdk/src/llvm-project /mnt/c/Workspace/llvm-project
cp -R /opt/wasi /mnt/c/Workspace/
rm -rf /mnt/c/Workspace/wasi/bin
```

2. x64 Native Tools Command Prompt for VS 2019

```cmd
cmake -GNinja ^
  -DCMAKE_BUILD_TYPE=MinSizeRel ^
  -DCMAKE_INSTALL_PREFIX=C:/Workspace/wasi ^
  -DLLVM_TARGETS_TO_BUILD=WebAssembly ^
  -DLLVM_DEFAULT_TARGET_TRIPLE=wasm32-wasi ^
  -DLLVM_ENABLE_PROJECTS="lld;clang" ^
  -DDEFAULT_SYSROOT=C:/Workspace/wasi/sysroot ^
  -B llvm-build llvm-project/llvm
cmake --build llvm-build --target install-clang
cmake --build llvm-build --target install-lld
cmake --build llvm-build --target install-llc
cmake --build llvm-build --target install-llvm-ar
cmake --build llvm-build --target install-llvm-ranlib
cmake --build llvm-build --target install-llvm-dwarfdump
cmake --build llvm-build --target install-llvm-nm
cmake --build llvm-build --target install-llvm-size
cmake --build llvm-build --target llvm-config
```

3. Command Prompt

```cmd
set Path=%Path%;C:\Workspace\wasi\bin
clang++ -std=c++2a -Oz main.cpp -o main.wasm
```

I was surprised to see that the resulting binary is 16.2 KB large and that I can't execute it in the browser.

```js
(async () => {
  const config = {
    env: {
      tableBase: 0,
      memoryBase: 0,
      table: new WebAssembly.Table({ initial: 0, element: "anyfunc" }),
      memory: new WebAssembly.Memory({ initial: 256 }),
    }
  };
  const { module, instance } = await WebAssembly.instantiateStreaming(fetch("main.wasm"), config);
  const result = instance.exports.main();
  console.log(result);
})();
```

resulted in the following error:

```
TypeError: WebAssembly.instantiate(): Import #0 module="wasi_unstable" error: module is not an object or function
```

I'd understand if I had to provide implementations for the entries in `undefined-symbols.txt` or linux syscalls in the `config.env` variable, but this looks like something wasi related went wrong.

Is there a documentation on how to *use* the wasi SDK?

**Comment by sbc100** [comment]
Browsers don't currently support WASI.   You would need some kind of runtime implementation such as this small/incomplete one that I maintain: https://github.com/WebAssembly/waterfall/blob/master/src/wasi.js

Outside the browser there are couple of ways you can run wasi binaries such as https://wasmer.io/ or https://github.com/CraneStation/wasmtime.

**Comment by qis** [comment]
Oh, then I completely misunderstood the purpose for this project. Sorry. :)
